ruby "2.2.0"
source "https://rubygems.org"

gem "jquery-datatables-rails", "~> 3.1.1", {:github=>"rweng/jquery-datatables-rails"}
gem "rails_presenter", "~> 0.0.3", {:github=>"dfmonaco/rails_presenter"}
gem "pry-rails", "~> 0.3.3"
gem "rails", "~> 4.2.0"
gem "sass-rails", "~> 5.0.1"
gem "uglifier", "~> 2.7.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails", "~> 4.0.3"
gem "jquery-ui-rails", "~> 5.0.3"
gem "jbuilder", "~> 2.2.8"
gem "thin", "~> 1.6.3"
gem "callable", "~> 0.0.3"
gem "rmagick", "~> 2.13.4"
gem "compass-rails", "~> 2.0.4"
gem "active_attr", "~> 0.8.5"
gem "rspec-rails", "~> 3.2.1"
gem "picasawebalbums", "~> 1.4.5", {:github=>"iachettifederico/PicasaWebAlbums", :require=>"PicasaWebAlbums"}
gem "htmlentities", "~> 4.3.3"
gem "pg", "~> 0.18.1"
gem "haml-rails", "~> 0.8.2"
gem "colorbox-rails", "~> 0.1.2"
gem "ckeditor_rails", "~> 4.4.6"
gem "simple_form", "~> 3.1.0"
gem "dotenv-rails", "~> 1.0.2"
gem "rails-i18n", "~> 4.0.4"
gem "devise", "~> 3.4.1"
gem "carrierwave", "~> 0.10.0"
gem "carrierwave-dropbox", "~> 1.2.1"
gem "dropbox-api", "~> 0.4.6"
gem "quiet_assets", "~> 1.1.0"
